name: setup nginx

on:
  push:

jobs:
  run-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Clone git
        uses: actions/checkout@v7

      - name: Install nginx
        uses: nyurik/action-setup-nginx@v1

      - name: Deploy HTML file to Nginx Web Root
        run: |
          sudo cp templates/index.html /var/www/html/index.html

      - name: Start nginx server
        run: |
          sudo systemctl start nginx || true
          sudo systemctl status nginx --no-pager
          sudo ss -tlnp | grep :80 || true

      - name: Check nginx
        run: |
          curl -v http://127.0.0.1:80
          
      - name: Install cloudflared
        run: |
          curl -L --output cloudflared.deb \
            https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Create tunnel
        run: |
          cloudflared tunnel --url http://localhost:80
